global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.Common;
global using CsabaDu.FooVaria.BaseTypes.Common.Factories;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Statics;
global using CsabaDu.FooVaria.Tests.TestHelpers.DynamicDataSources.ObjectArrayItems;
global using CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes;
global using CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.Factories;
global using CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.Returns;
global using CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.Types;
global using CsabaDu.FooVaria.Tests.TestHelpers.Params;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using System.ComponentModel;
global using static CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types.Implementations.BaseMeasurement;
global using static CsabaDu.FooVaria.BaseTypes.Measurables.Types.Implementations.Measurable;
global using static CsabaDu.FooVaria.Tests.TestHelpers.Params.TestSupport;
