global using CsabaDu.FooVaria.BaseTypes.Common;
global using CsabaDu.FooVaria.BaseTypes.Common.Factories;
global using CsabaDu.FooVaria.BaseTypes.Common.Types;
global using CsabaDu.FooVaria.BaseTypes.Common.Types.Implementations;
global using CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes;
global using CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.Returns;
global using CsabaDu.FooVaria.Tests.TestHelpers.Params;
global using CsabaDu.FooVaria.Tests.UnitTests.BaseTypes.CommonTests.Fakes;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
