global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics;
global using CsabaDu.FooVaria.BaseTypes.Common;
global using CsabaDu.FooVaria.BaseTypes.Common.Factories;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Statics;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types;
global using CsabaDu.FooVaria.BaseTypes.Spreads.Factories;
global using CsabaDu.FooVaria.BaseTypes.Spreads.Types;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes.Returns;
global using CsabaDu.FooVaria.Tests.TestHelpers.Params;
global using System.ComponentModel;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types.Implementations.BaseMeasurement;
global using static CsabaDu.FooVaria.BaseTypes.Measurables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.Measurables.Types.Implementations.Measurable;
global using static CsabaDu.FooVaria.Tests.TestHelpers.HelperMethods.TestSupport;
global using CsabaDu.FooVaria.Tests.UnitTests.BaseTypes.BaseMeasuresTests.Fakes;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Enums;