global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.Common;
global using CsabaDu.FooVaria.BaseTypes.Common.Factories;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Factories;
global using CsabaDu.FooVaria.Tests.TestHelpers.Fakes;
global using CsabaDu.FooVaria.Tests.TestHelpers.Fakes.Returns;
global using CsabaDu.FooVaria.Tests.TestHelpers.Params;
global using CsabaDu.FooVaria.Tests.UnitTests.BaseTypes.BaseQuantifiablesTests.Fakes;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using static CsabaDu.FooVaria.BaseTypes.Measurables.Types.Implementations.Measurable;
