global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasures.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasures.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasures.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Common;
global using CsabaDu.FooVaria.BaseTypes.Common.Factories;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes.Returns;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.Tests.UnitTests.BaseTypes.BaseMeasuresTests.Fakes.BaseMeasureFactoryObject;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics;
global using CsabaDu.FooVaria.Tests.UnitTests.BaseTypes.BaseMeasurementsTests.Fakes;
