global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasures.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Statics;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes.ObjectArrays;
global using CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.BaseMeasures;
global using CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.BaseQuantifiables;
global using CsabaDu.FooVaria.Tests.TestHelpers.HelperMethods;
global using CsabaDu.FooVaria.Tests.TestHelpers.Params;
global using System.ComponentModel;
global using System.Reflection;
global using static CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types.Implementations.BaseMeasurement;
global using static CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.BaseMeasurements.BaseMeasurementChild;
global using static CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.BaseMeasures.BaseMeasureChild;
global using static CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.Quantifiables.LimiterQuantifiableObject;
global using static CsabaDu.FooVaria.Tests.TestHelpers.HelperMethods.TestSupport;
