global using CsabaDu.FooVaria.BaseMeasurements.Types;
global using CsabaDu.FooVaria.BaseMeasures.Types;
global using CsabaDu.FooVaria.BaseRates.Behaviors;
global using CsabaDu.FooVaria.BaseRates.Factories;
global using CsabaDu.FooVaria.BaseRates.Types;
global using CsabaDu.FooVaria.BaseRates.Types.Implementations;
global using CsabaDu.FooVaria.Measurables.Behaviors;
global using CsabaDu.FooVaria.Measurables.Enums;
global using CsabaDu.FooVaria.Measurables.Statics;
global using CsabaDu.FooVaria.Measures.Factories;
global using CsabaDu.FooVaria.Proportions.Factories;
global using CsabaDu.FooVaria.Proportions.Types;
global using CsabaDu.FooVaria.Proportions.Types.Implementations;
global using CsabaDu.FooVaria.Quantifiables.Statics;
global using static CsabaDu.FooVaria.BaseMeasurements.Statics.MeasureUnits;
global using static CsabaDu.FooVaria.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Measurables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Quantifiables.Statics.ExceptionMethods;
