global using CsabaDu.FooVaria.AbstractTypes.SimpleRates.Factories;
global using CsabaDu.FooVaria.AbstractTypes.SimpleRates.Types;
global using CsabaDu.FooVaria.AbstractTypes.SimpleRates.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasures.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseRates.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseRates.Types;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Statics;
global using CsabaDu.FooVaria.Measures.Factories;
global using CsabaDu.FooVaria.Measures.Types;
global using CsabaDu.FooVaria.Proportions.Factories;
global using CsabaDu.FooVaria.Proportions.Types;
global using CsabaDu.FooVaria.Proportions.Types.Implementations;
global using static CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types.Implementations.BaseMeasurement;
global using static CsabaDu.FooVaria.BaseTypes.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.Measurables.Statics.ExceptionMethods;
