global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes.ObjectArrays;
global using CsabaDu.FooVaria.Tests.TestHelpers.Params;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Reflection;
global using static CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types.Implementations.BaseMeasurement;
global using static CsabaDu.FooVaria.Tests.TestHelpers.HelperMethods.TestSupport;
