global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Statics;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types;
global using CsabaDu.FooVaria.BaseTypes.Shapes.Factories;
global using CsabaDu.FooVaria.BaseTypes.Shapes.Types;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes.ObjectArrays;
global using CsabaDu.FooVaria.Tests.TestHelpers.TestDoubles.BaseTypes.BaseQuantifiables;
global using CsabaDu.FooVaria.Tests.TestHelpers.TestDoubles.BaseTypes.Shapes;
global using CsabaDu.FooVaria.Tests.TestHelpers.HelperMethods;
global using CsabaDu.FooVaria.Tests.TestHelpers.Params;
global using System.ComponentModel;
global using System.Reflection;
global using static CsabaDu.FooVaria.Tests.TestHelpers.TestDoubles.BaseTypes.Quantifiables.LimiterQuantifiableObject;
global using static CsabaDu.FooVaria.Tests.TestHelpers.TestDoubles.BaseTypes.Quantifiables.QuantifiableChild;
global using static CsabaDu.FooVaria.Tests.TestHelpers.TestDoubles.BaseTypes.Quantifiables.ShapeComponentQuantifiableObject;
global using static CsabaDu.FooVaria.Tests.TestHelpers.TestDoubles.BaseTypes.Shapes.LimiterShapeObject;
global using static CsabaDu.FooVaria.Tests.TestHelpers.TestDoubles.BaseTypes.Shapes.ShapeChild;
global using static CsabaDu.FooVaria.Tests.TestHelpers.HelperMethods.TestSupport;
