global using CsabaDu.FooVaria.BaseSpreads.Factories;
global using CsabaDu.FooVaria.BaseSpreads.Types;
global using CsabaDu.FooVaria.Common.Factories;
global using CsabaDu.FooVaria.Common.Types;
global using CsabaDu.FooVaria.Masses.Behaviors;
global using CsabaDu.FooVaria.Masses.Factories;
global using CsabaDu.FooVaria.Masses.Types;
global using CsabaDu.FooVaria.Masses.Types.Implementations;
global using CsabaDu.FooVaria.Measurables.Enums;
global using CsabaDu.FooVaria.Measures.Types;
global using CsabaDu.FooVaria.Proportions.Factories;
global using CsabaDu.FooVaria.Proportions.Types;
global using CsabaDu.FooVaria.Quantifiables.Types;
global using CsabaDu.FooVaria.Quantifiables.Types.Implementations;
global using CsabaDu.FooVaria.RateComponents.Factories;
global using CsabaDu.FooVaria.Shapes.Types;
global using CsabaDu.FooVaria.SimpleShapes.Factories;
global using CsabaDu.FooVaria.SimpleShapes.Types;
global using CsabaDu.FooVaria.Spreads.Factories;
global using CsabaDu.FooVaria.Spreads.Types;
global using static CsabaDu.FooVaria.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Measurables.Statics.MeasureUnits;
global using static CsabaDu.FooVaria.Quantifiables.Statics.ExceptionMethods;
