global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasures.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseShapes.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseSpreads.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseSpreads.Types;
global using CsabaDu.FooVaria.BaseTypes.Common.Factories;
global using CsabaDu.FooVaria.BaseTypes.Common.Types;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Factories;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Statics;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types.Implementations;
global using CsabaDu.FooVaria.Masses.Behaviors;
global using CsabaDu.FooVaria.Masses.Factories;
global using CsabaDu.FooVaria.Masses.Types;
global using CsabaDu.FooVaria.Masses.Types.Implementations;
global using CsabaDu.FooVaria.Measures.Factories;
global using CsabaDu.FooVaria.Measures.Types;
global using CsabaDu.FooVaria.Proportions.Factories;
global using CsabaDu.FooVaria.Proportions.Types;
global using CsabaDu.FooVaria.Shapes.Factories;
global using CsabaDu.FooVaria.Shapes.Types;
global using CsabaDu.FooVaria.Spreads.Factories;
global using CsabaDu.FooVaria.Spreads.Types;
global using static CsabaDu.FooVaria.BaseTypes.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.Measurables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.Quantifiables.Statics.ExceptionMethods;
