global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasures.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasures.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasures.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.Common.Factories;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Factories;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Types;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Statics;
global using CsabaDu.FooVaria.Measurements.Factories;
global using CsabaDu.FooVaria.Measurements.Types;
global using CsabaDu.FooVaria.RateComponents.Factories;
global using CsabaDu.FooVaria.RateComponents.Types;
global using CsabaDu.FooVaria.RateComponents.Types.Implementations;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.BaseTypes.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.Quantifiables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.Quantifiables.Statics.QuantityTypes;

