global using CsabaDu.FooVaria.BaseMeasurements.Types;
global using CsabaDu.FooVaria.BaseMeasures.Factories;
global using CsabaDu.FooVaria.BaseMeasures.Types;
global using CsabaDu.FooVaria.BaseMeasures.Types.Implementations;
global using CsabaDu.FooVaria.Measurables.Enums;
global using CsabaDu.FooVaria.Measurables.Types;
global using CsabaDu.FooVaria.Measurements.Factories;
global using CsabaDu.FooVaria.Measurements.Types;
global using CsabaDu.FooVaria.Measures.Types;
global using CsabaDu.FooVaria.Quantifiables.Behaviors;
global using CsabaDu.FooVaria.Quantifiables.Enums;
global using CsabaDu.FooVaria.Quantifiables.Statics;
global using CsabaDu.FooVaria.Quantifiables.Types.Implementations;
global using CsabaDu.FooVaria.RateComponents.Factories;
global using CsabaDu.FooVaria.RateComponents.Types;
global using CsabaDu.FooVaria.RateComponents.Types.Implementations;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Quantifiables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Quantifiables.Statics.QuantityTypes;
