global using CsabaDu.FooVaria.BaseShapes.Behaviors;
global using CsabaDu.FooVaria.BaseShapes.Factories;
global using CsabaDu.FooVaria.BaseShapes.Types;
global using CsabaDu.FooVaria.BaseSpreads.Factories;
global using CsabaDu.FooVaria.BaseSpreads.Types;
global using CsabaDu.FooVaria.BaseSpreads.Types.Implementations;
global using CsabaDu.FooVaria.Common.Types.Implementations;
global using CsabaDu.FooVaria.Quantifiables.Behaviors;
global using CsabaDu.FooVaria.Quantifiables.Types;
