global using CsabaDu.FooVaria.Shapes.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasures.Types;
global using CsabaDu.FooVaria.BaseTypes.Shapes.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.Shapes.Factories;
global using CsabaDu.FooVaria.BaseTypes.Shapes.Types;
global using CsabaDu.FooVaria.BaseTypes.Shapes.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.Spreads.Types;
global using CsabaDu.FooVaria.BaseTypes.Common.Enums;
global using CsabaDu.FooVaria.BaseTypes.Common.Factories;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Types;
global using CsabaDu.FooVaria.Measures.Factories;
global using CsabaDu.FooVaria.Measures.Types;
global using CsabaDu.FooVaria.AbstractTypes.SimpleShapes.Behaviors;
global using CsabaDu.FooVaria.AbstractTypes.SimpleShapes.Enums;
global using CsabaDu.FooVaria.AbstractTypes.SimpleShapes.Factories;
global using CsabaDu.FooVaria.AbstractTypes.SimpleShapes.Types;
global using CsabaDu.FooVaria.BulkSpreads.Factories;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types.Implementations.BaseMeasurement;
global using static CsabaDu.FooVaria.BaseTypes.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.Measurables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.AbstractTypes.SimpleShapes.Statics.ExceptionMethods;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Behaviors;
