global using CsabaDu.FooVaria.Common.Behaviors;
global using CsabaDu.FooVaria.Common.Factories;
global using CsabaDu.FooVaria.Common.Types;
global using CsabaDu.FooVaria.Common.Types.Implementations;
global using CsabaDu.FooVaria.Measurables.Behaviors;
global using CsabaDu.FooVaria.Measurables.Enums;
global using CsabaDu.FooVaria.Measurables.Factories;
global using CsabaDu.FooVaria.Measurables.Types;
global using static CsabaDu.FooVaria.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Measurables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Measurables.Statics.Extensions;
global using static CsabaDu.FooVaria.Measurables.Statics.MeasureUnits;
global using static CsabaDu.FooVaria.Measurables.Statics.MeasureUnitTypes;
global using static CsabaDu.FooVaria.Measurables.Types.Implementations.BaseMeasurement;
