global using CsabaDu.FooVaria.AbstractTypes.ComplexShapes.Factories;
global using CsabaDu.FooVaria.AbstractTypes.SimpleShapes.Factories;
global using CsabaDu.FooVaria.AbstractTypes.SimpleShapes.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.Shapes.Factories;
global using CsabaDu.FooVaria.BaseTypes.Shapes.Types;
global using CsabaDu.FooVaria.BaseTypes.Shapes.Types.Implementations;
global using CsabaDu.FooVaria.Measures.Types;
global using static CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.Common.Statics.ExceptionMethods;
