global using CsabaDu.FooVaria.Common.Enums;
global using CsabaDu.FooVaria.Common.Factories;
global using CsabaDu.FooVaria.Measurables.Behaviors;
global using CsabaDu.FooVaria.Measurables.Factories;
global using CsabaDu.FooVaria.Measurables.Statics;
global using CsabaDu.FooVaria.Measurables.Types;
global using CsabaDu.FooVaria.Measurables.Types.Implementations;
global using CsabaDu.FooVaria.Quantifiables.Behaviors;
global using CsabaDu.FooVaria.Quantifiables.Factories;
global using CsabaDu.FooVaria.Quantifiables.Types;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Measurables.Statics.MeasureUnitTypes;
global using static CsabaDu.FooVaria.Quantifiables.Statics.QuantityTypes;
