global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics;
global using CsabaDu.FooVaria.BaseTypes.BaseRates.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseRates.Types;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Types;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes.ObjectArrays;
global using CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.BaseQuantifiables;
global using CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.BaseRates;
global using CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.Quantifiables;
global using CsabaDu.FooVaria.Tests.TestHelpers.Params;
global using System.ComponentModel;
global using System.Reflection;
global using static CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.BaseRates.BaseRateChild;
global using static CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.BaseRates.LimiterBaseRateObject;
global using static CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.Measurables.MeasurableChild;
global using static CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.Quantifiables.QuantifiableChild;
