global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics;
global using CsabaDu.FooVaria.BaseTypes.BaseRates.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseRates.Types;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Types;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes.ArgsArrays;
global using CsabaDu.FooVaria.Tests.TestHelpers.TestDoubles.BaseTypes.BaseQuantifiables;
global using CsabaDu.FooVaria.Tests.TestHelpers.TestDoubles.BaseTypes.BaseRates;
global using CsabaDu.FooVaria.Tests.TestHelpers.HelperMethods;
global using CsabaDu.FooVaria.Tests.TestHelpers.Params;
global using System.ComponentModel;
global using System.Reflection;
global using static CsabaDu.FooVaria.Tests.TestHelpers.TestDoubles.BaseTypes.BaseRates.BaseRateChild;
global using static CsabaDu.FooVaria.Tests.TestHelpers.TestDoubles.BaseTypes.BaseRates.LimiterBaseRateObject;
global using static CsabaDu.FooVaria.Tests.TestHelpers.TestDoubles.BaseTypes.Measurables.MeasurableChild;
global using static CsabaDu.FooVaria.Tests.TestHelpers.TestDoubles.BaseTypes.Quantifiables.QuantifiableChild;
global using static CsabaDu.FooVaria.Tests.TestHelpers.HelperMethods.TestSupport;
