global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Statics;
global using System.Reflection;
global using static CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types.Implementations.BaseMeasurement;
global using static CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Types.Implementations.BaseQuantifiable;
global using static CsabaDu.FooVaria.BaseTypes.Measurables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.Measurables.Types.Implementations.Measurable;
global using static CsabaDu.FooVaria.Tests.TestHelpers.Params.SampleParams;
