global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasures.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasures.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasures.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Types;
global using CsabaDu.FooVaria.BaseTypes.Common.Factories;
global using CsabaDu.FooVaria.BaseTypes.Common.Types;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Factories;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types.Implementations;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types.Implementations.BaseMeasurement;
global using static CsabaDu.FooVaria.BaseTypes.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.Measurables.Statics.ExceptionMethods;
