global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Types;
global using CsabaDu.FooVaria.BaseTypes.Common;
global using CsabaDu.FooVaria.BaseTypes.Common.Enums;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types;
global using CsabaDu.FooVaria.BaseTypes.Shapes.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.Shapes.Enums;
global using CsabaDu.FooVaria.BaseTypes.Shapes.Factories;
global using CsabaDu.FooVaria.BaseTypes.Shapes.Types;
global using CsabaDu.FooVaria.BaseTypes.Spreads.Factories;
global using CsabaDu.FooVaria.BaseTypes.Spreads.Types;
global using CsabaDu.FooVaria.BaseTypes.Spreads.Types.Implementations;
global using System.ComponentModel;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.BaseTypes.Common.Statics.ExceptionMethods;
