global using CsabaDu.FooVaria.BaseMeasurements.Behaviors;
global using CsabaDu.FooVaria.BaseMeasurements.Factories;
global using CsabaDu.FooVaria.BaseMeasurements.Types;
global using CsabaDu.FooVaria.Common.Behaviors;
global using CsabaDu.FooVaria.Measurables.Behaviors;
global using CsabaDu.FooVaria.Measurables.Enums;
global using CsabaDu.FooVaria.Measurables.Factories;
global using CsabaDu.FooVaria.Measurables.Statics;
global using CsabaDu.FooVaria.Measurables.Types;
global using CsabaDu.FooVaria.Measurables.Types.Implementations;
global using static CsabaDu.FooVaria.BaseMeasurements.Statics.MeasureUnits;
global using static CsabaDu.FooVaria.BaseMeasurements.Types.Implementations.BaseMeasurement;
global using static CsabaDu.FooVaria.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Measurables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Measurables.Statics.MeasureUnitTypes;
