global using CsabaDu.FooVaria.Common.Enums;
global using CsabaDu.FooVaria.Common.Factories;
global using CsabaDu.FooVaria.Common.Types;
global using CsabaDu.FooVaria.Measurements.Types;
global using CsabaDu.FooVaria.Measures.Types;
global using CsabaDu.FooVaria.RateComponents.Factories;
global using CsabaDu.FooVaria.RateComponents.Types;
global using CsabaDu.FooVaria.Rates.Factories;
global using CsabaDu.FooVaria.Rates.Types;
global using CsabaDu.FooVaria.Rates.Types.Implementations;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Measurables.Statics.MeasureUnits;
