global using CsabaDu.FooVaria.BaseMeasurements.Types;
global using CsabaDu.FooVaria.BaseMeasurements.Types.Implementations;
global using CsabaDu.FooVaria.BaseMeasures.Types;
global using CsabaDu.FooVaria.BaseMeasures.Types.Implementations;
global using CsabaDu.FooVaria.BaseRates.Behaviors;
global using CsabaDu.FooVaria.BaseRates.Factories;
global using CsabaDu.FooVaria.BaseRates.Types;
global using CsabaDu.FooVaria.BaseRates.Types.Implementations;
global using CsabaDu.FooVaria.Common.Factories;
global using CsabaDu.FooVaria.Common.Types;
global using CsabaDu.FooVaria.Measurables.Enums;
global using CsabaDu.FooVaria.Measurables.Statics;
global using CsabaDu.FooVaria.Measurables.Types;
global using CsabaDu.FooVaria.Measurements.Types;
global using CsabaDu.FooVaria.Measures.Types;
global using CsabaDu.FooVaria.Quantifiables.Behaviors;
global using CsabaDu.FooVaria.Quantifiables.Enums;
global using CsabaDu.FooVaria.Quantifiables.Statics;
global using CsabaDu.FooVaria.RateComponents.Factories;
global using CsabaDu.FooVaria.RateComponents.Types;
global using CsabaDu.FooVaria.Rates.Factories;
global using CsabaDu.FooVaria.Rates.Types;
global using CsabaDu.FooVaria.Rates.Types.Implementations;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.BaseMeasurements.Statics.MeasureUnits;
global using static CsabaDu.FooVaria.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Measurables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Quantifiables.Statics.ExceptionMethods;
