global using CsabaDu.FooVaria.Common.Behaviors;
global using CsabaDu.FooVaria.Common.Enums;
global using CsabaDu.FooVaria.Common.Factories;
global using CsabaDu.FooVaria.Common.Statics;
global using CsabaDu.FooVaria.Common.Types;
global using CsabaDu.FooVaria.Common.Types.Implementations;
global using CsabaDu.FooVaria.Measurements.Types;
global using CsabaDu.FooVaria.RateComponents.Factories;
global using CsabaDu.FooVaria.RateComponents.Types;
global using CsabaDu.FooVaria.Rates.Factories;
global using CsabaDu.FooVaria.Rates.Types;
global using static CsabaDu.FooVaria.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Common.Statics.MeasureUnits;
