global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseRates.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseRates.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseRates.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseRates.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Statics;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Types;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types;
global using CsabaDu.FooVaria.Measures.Factories;
global using CsabaDu.FooVaria.Measures.Types;
global using CsabaDu.FooVaria.ProportionLimits.Factories;
global using CsabaDu.FooVaria.ProportionLimits.Types;
global using CsabaDu.FooVaria.ProportionLimits.Types.Implementations;
global using CsabaDu.FooVaria.Proportions.Factories;
global using CsabaDu.FooVaria.Proportions.Types;
global using CsabaDu.FooVaria.Proportions.Types.Implementations;
global using CsabaDu.FooVaria.SimpleRates.Factories;
global using CsabaDu.FooVaria.SimpleRates.Factories.Implementations;
global using CsabaDu.FooVaria.SimpleRates.Types;
global using CsabaDu.FooVaria.SimpleRates.Types.Implementations;
global using System.ComponentModel;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types.Implementations.BaseMeasurement;
global using static CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.Common.Statics.ExceptionMethods;
