global using CsabaDu.FooVaria.Common.Behaviors;
global using CsabaDu.FooVaria.Common.Enums;
global using CsabaDu.FooVaria.Common.Enums.MeasureUnits;
global using CsabaDu.FooVaria.Common.Factories;
global using CsabaDu.FooVaria.Common.Statics;
global using CsabaDu.FooVaria.Common.Types;
global using CsabaDu.FooVaria.Common.Types.Implementations;
global using CsabaDu.FooVaria.RateComponents.Types;
global using CsabaDu.FooVaria.RateComponents.Types.MeasureTypes;
global using CsabaDu.FooVaria.Spreads.Factories;
global using CsabaDu.FooVaria.Spreads.Statics;
global using CsabaDu.FooVaria.Spreads.Types;
global using static CsabaDu.FooVaria.Common.Statics.ExceptionMethods;
