global using CsabaDu.FooVaria.Common.Enums;
global using CsabaDu.FooVaria.Common.Enums.MeasureUnits;
global using CsabaDu.FooVaria.Common.Factories;
global using CsabaDu.FooVaria.Common.Types;
global using CsabaDu.FooVaria.Common.Types.Implementations;
global using CsabaDu.FooVaria.Quantifiables.Behaviors;
global using CsabaDu.FooVaria.Quantifiables.Factories;
global using CsabaDu.FooVaria.Quantifiables.Types;
global using CsabaDu.FooVaria.RateComponents.Factories;
global using CsabaDu.FooVaria.RateComponents.Types;
global using CsabaDu.FooVaria.RateComponents.Types.MeasureTypes;
global using CsabaDu.FooVaria.Shapes.Behaviors;
global using CsabaDu.FooVaria.Shapes.Factories;
global using CsabaDu.FooVaria.Shapes.Types;
global using CsabaDu.FooVaria.SimpleShapes.Behaviors;
global using CsabaDu.FooVaria.SimpleShapes.Enums;
global using CsabaDu.FooVaria.SimpleShapes.Factories;
global using CsabaDu.FooVaria.SimpleShapes.Statics;
global using CsabaDu.FooVaria.SimpleShapes.Types;
global using CsabaDu.FooVaria.SimpleShapes.Types.Implementations;
global using CsabaDu.FooVaria.Spreads.Factories;
global using CsabaDu.FooVaria.Spreads.Types;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Common.Statics.Extensions;
global using static CsabaDu.FooVaria.Measurables.Statics.MeasureUnitTypes;
global using static CsabaDu.FooVaria.SimpleShapes.Statics.ExceptionMethods;
