global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Statics;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Factories;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes.BehaviorObjects;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes.ObjectArrays;
global using CsabaDu.FooVaria.Tests.TestHelpers.Params;
//global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using System.ComponentModel;
global using static CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Types.Implementations.BaseQuantifiable;
global using static CsabaDu.FooVaria.Tests.TestHelpers.HelperMethods.TestSupport;
