global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics;
global using CsabaDu.FooVaria.BaseTypes.Common;
global using CsabaDu.FooVaria.BaseTypes.Common.Factories;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Statics;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Factories;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types.Implementations;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes.BehaviorObjects;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes.ObjectArrayItems;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes.Returns;
global using CsabaDu.FooVaria.Tests.TestHelpers.Params;
global using CsabaDu.FooVaria.Tests.UnitTests.BaseTypes.QuantifiablesTests.Fakes;
//global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using System.ComponentModel;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Types.Implementations.BaseQuantifiable;
global using static CsabaDu.FooVaria.BaseTypes.Measurables.Types.Implementations.Measurable;
global using static CsabaDu.FooVaria.Tests.TestHelpers.HelperMethods.TestSupport;
global using static CsabaDu.FooVaria.Tests.UnitTests.BaseTypes.QuantifiablesTests.Fakes.LimiterQuantifiableObject;
global using static CsabaDu.FooVaria.Tests.UnitTests.BaseTypes.QuantifiablesTests.Fakes.QuantifiableChild;
