global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.BaseRates.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseRates.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseRates.Types;
global using CsabaDu.FooVaria.BaseTypes.Common.Statics;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Types;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Factories;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types;
global using static CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.Common.Statics.ExceptionMethods;
