global using CsabaDu.FooVaria.Common.Behaviors;
global using CsabaDu.FooVaria.Common.Enums;
global using CsabaDu.FooVaria.Common.Enums.MeasureUnits;
global using CsabaDu.FooVaria.Common.Factories;
global using CsabaDu.FooVaria.Common.Types;
global using System.ComponentModel;
global using static CsabaDu.FooVaria.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Common.Statics.Extensions;
global using static CsabaDu.FooVaria.Common.Statics.MeasureUnitTypes;
global using static CsabaDu.FooVaria.Common.Statics.QuantityTypes;
