global using CsabaDu.FooVaria.BaseMeasurements.Factories;
global using CsabaDu.FooVaria.BaseMeasurements.Statics;
global using CsabaDu.FooVaria.BaseMeasurements.Types;
global using CsabaDu.FooVaria.BaseMeasurements.Types.Implementations;
global using CsabaDu.FooVaria.Common.Factories;
global using CsabaDu.FooVaria.Common.Statics;
global using CsabaDu.FooVaria.Measurables.Enums;
global using CsabaDu.FooVaria.Measurables.Factories;
global using CsabaDu.FooVaria.Measurables.Statics;
global using CsabaDu.FooVaria.Measurables.Types;
global using CsabaDu.FooVaria.Measurements.Behaviors;
global using CsabaDu.FooVaria.Measurements.Factories;
global using CsabaDu.FooVaria.Measurements.Types;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.BaseMeasurements.Statics.MeasureUnits;
global using static CsabaDu.FooVaria.BaseMeasurements.Types.Implementations.BaseMeasurement;
global using static CsabaDu.FooVaria.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Common.Statics.Extensions;
global using static CsabaDu.FooVaria.Measurables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Measurables.Statics.MeasureUnitTypes;
