global using CsabaDu.FooVaria.Common;
global using CsabaDu.FooVaria.Common.Behaviors;
global using CsabaDu.FooVaria.Common.Enums;
global using CsabaDu.FooVaria.Common.Enums.MeasureUnits;
global using CsabaDu.FooVaria.Common.Factories;
global using CsabaDu.FooVaria.Common.Statics;
global using CsabaDu.FooVaria.Common.Types;
global using CsabaDu.FooVaria.Common.Types.Implementations;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.Common.Statics.ExceptionMethods;
global using CsabaDu.FooVaria.Measurements.Behaviors;
global using CsabaDu.FooVaria.Measurements.Factories;
global using CsabaDu.FooVaria.Measurements.Types;