global using CsabaDu.FooVaria.AbstractTypes.SimpleRates.Factories;
global using CsabaDu.FooVaria.AbstractTypes.SimpleRates.Factories.Implementations;
global using CsabaDu.FooVaria.AbstractTypes.SimpleRates.Types;
global using CsabaDu.FooVaria.AbstractTypes.SimpleRates.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasures.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.BaseRates.Types;
global using CsabaDu.FooVaria.BaseTypes.Common.Factories;
global using CsabaDu.FooVaria.BaseTypes.Common.Types;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Statics;
global using CsabaDu.FooVaria.ProportionLimits.Factories;
global using CsabaDu.FooVaria.ProportionLimits.Types;
global using CsabaDu.FooVaria.ProportionLimits.Types.Implementations;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.BaseTypes.Common.Statics.ExceptionMethods;
