global using CsabaDu.FooVaria.Common.Behaviors;
global using CsabaDu.FooVaria.Common.Enums;
global using CsabaDu.FooVaria.Common.Enums.MeasureUnits;
global using CsabaDu.FooVaria.Common.Factories;
global using CsabaDu.FooVaria.Common.Types;
global using CsabaDu.FooVaria.Common.Types.Implementations;
global using CsabaDu.FooVaria.RateComponents.Factories.Implementations;
global using CsabaDu.FooVaria.RateComponents.Types.MeasureTypes;
global using CsabaDu.FooVaria.Shapes.Behaviors;
global using CsabaDu.FooVaria.Shapes.Enums;
global using CsabaDu.FooVaria.Shapes.Factories;
global using CsabaDu.FooVaria.Spreads.Statics;
global using static CsabaDu.FooVaria.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.RateComponents.Statics.Extensions;
global using static CsabaDu.FooVaria.Shapes.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Common.Statics.Extensions;