global using CsabaDu.FooVaria.BaseShapes.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasures.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseShapes.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseShapes.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseShapes.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseShapes.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.BaseSpreads.Types;
global using CsabaDu.FooVaria.BaseTypes.Common.Enums;
global using CsabaDu.FooVaria.BaseTypes.Common.Factories;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Statics;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types;
global using CsabaDu.FooVaria.Measures.Factories;
global using CsabaDu.FooVaria.Measures.Types;
global using CsabaDu.FooVaria.Shapes.Behaviors;
global using CsabaDu.FooVaria.Shapes.Enums;
global using CsabaDu.FooVaria.Shapes.Factories;
global using CsabaDu.FooVaria.Shapes.Types;
global using CsabaDu.FooVaria.Spreads.Factories;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types.Implementations.BaseMeasurement;
global using static CsabaDu.FooVaria.BaseTypes.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.Measurables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.Quantifiables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.Shapes.Statics.ExceptionMethods;
