global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.Common;
global using CsabaDu.FooVaria.BaseTypes.Common.Factories;
global using CsabaDu.FooVaria.BaseTypes.Common.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Factories;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Types.Implementations;
global using CsabaDu.FooVaria.Measurements.Types.Implementations;
global using CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.Returns;
global using CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes;
global using static CsabaDu.FooVaria.BaseTypes.Measurables.Types.Implementations.Measurable;
