global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasures.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasures.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseMeasures.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.BaseRates.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseRates.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseRates.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.Common;
global using CsabaDu.FooVaria.BaseTypes.Common.Factories;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Factories;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Statics;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Types;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Factories;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.Shapes.Factories;
global using CsabaDu.FooVaria.BaseTypes.Shapes.Types;
global using CsabaDu.FooVaria.BaseTypes.Shapes.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.Spreads.Factories;
global using CsabaDu.FooVaria.BaseTypes.Spreads.Types;
global using CsabaDu.FooVaria.BaseTypes.Spreads.Types.Implementations;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes.ReturnValues;
global using CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.Quantifiables;
global using CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.Spreads;
global using CsabaDu.FooVaria.Tests.TestHelpers.HelperMethods;
global using System.ComponentModel;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types.Implementations.BaseMeasurement;
global using static CsabaDu.FooVaria.BaseTypes.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.Measurables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.Measurables.Types.Implementations.Measurable;
global using static CsabaDu.FooVaria.Tests.TestHelpers.DataTypes.DataFields;
global using static CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.BaseMeasures.BaseMeasureFactoryObject;
global using static CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.BaseMeasures.SpreadMeasureBaseMeasureObject;
global using static CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.Quantifiables.QuantifiableChild;
global using static CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.Quantifiables.ShapeComponentQuantifiableObject;
global using static CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.Shapes.ShapeChild;
global using static CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.Spreads.ShapeComponentSpreadMeasureObject;
global using static CsabaDu.FooVaria.Tests.TestHelpers.Fakes.BaseTypes.Spreads.SpreadChild;
