global using CsabaDu.FooVaria.AbstractTypes.SimpleShapes.Behaviors;
global using CsabaDu.FooVaria.AbstractTypes.SimpleShapes.Factories;
global using CsabaDu.FooVaria.AbstractTypes.SimpleShapes.Factories.Implementations;
global using CsabaDu.FooVaria.AbstractTypes.SimpleShapes.Types;
global using CsabaDu.FooVaria.AbstractTypes.SimpleShapes.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Types;
global using CsabaDu.FooVaria.BaseTypes.Common.Enums;
global using CsabaDu.FooVaria.BaseTypes.Common.Types;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types;
global using CsabaDu.FooVaria.BaseTypes.Shapes.Enums;
global using CsabaDu.FooVaria.BaseTypes.Shapes.Types;
global using CsabaDu.FooVaria.BaseTypes.Spreads.Factories;
global using CsabaDu.FooVaria.BaseTypes.Spreads.Types;
global using CsabaDu.FooVaria.BulkSpreads.Factories;
global using CsabaDu.FooVaria.Measures.Types;
global using CsabaDu.FooVaria.PlaneShapes.Factories;
global using CsabaDu.FooVaria.PlaneShapes.Types;
global using CsabaDu.FooVaria.PlaneShapes.Types.Implementations;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types.Implementations.BaseMeasurement;
global using static CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Types.Implementations.BaseQuantifiable;
global using static CsabaDu.FooVaria.BaseTypes.Common.Statics.ExceptionMethods;
