global using CsabaDu.FooVaria.BaseTypes.BaseShapes.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseSpreads.Factories;
global using CsabaDu.FooVaria.BaseTypes.BaseSpreads.Types;
global using CsabaDu.FooVaria.BaseTypes.Common.Enums;
global using CsabaDu.FooVaria.BaseTypes.Common.Types;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Behaviors;
global using CsabaDu.FooVaria.Measures.Types;
global using CsabaDu.FooVaria.PlaneShapes.Factories;
global using CsabaDu.FooVaria.PlaneShapes.Types;
global using CsabaDu.FooVaria.PlaneShapes.Types.Implementations;
global using CsabaDu.FooVaria.Shapes.Behaviors;
global using CsabaDu.FooVaria.Shapes.Enums;
global using CsabaDu.FooVaria.Shapes.Factories;
global using CsabaDu.FooVaria.Shapes.Factories.Implementations;
global using CsabaDu.FooVaria.Shapes.Types;
global using CsabaDu.FooVaria.Shapes.Types.Implementations;
global using CsabaDu.FooVaria.Spreads.Factories;
global using static CsabaDu.FooVaria.BaseTypes.BaseMeasurements.Types.Implementations.BaseMeasurement;
global using static CsabaDu.FooVaria.BaseTypes.Common.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.Measurables.Types.Implementations.Measurable;
global using static CsabaDu.FooVaria.BaseTypes.Quantifiables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.Quantifiables.Types.Implementations.Quantifiable;
global using static CsabaDu.FooVaria.Shapes.Types.Implementations.Shape;
