global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Enums;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Types;
global using CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Types.Implementations;
global using CsabaDu.FooVaria.BaseTypes.Common;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.Measurables.Enums;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Behaviors;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Factories;
global using CsabaDu.FooVaria.BaseTypes.Quantifiables.Types;
global using System.Diagnostics.CodeAnalysis;
global using static CsabaDu.FooVaria.BaseTypes.BaseQuantifiables.Statics.ExceptionMethods;
global using static CsabaDu.FooVaria.BaseTypes.Measurables.Statics.ExceptionMethods;
