global using CsabaDu.FooVaria.BaseTypes.Common;
global using CsabaDu.FooVaria.BaseTypes.Common.Factories;
global using CsabaDu.FooVaria.BaseTypes.Common.Types;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes;
global using CsabaDu.FooVaria.Tests.TestHelpers.DataTypes.ArgsArrays;
global using CsabaDu.FooVaria.Tests.TestHelpers.Params;
global using CsabaDu.FooVaria.Tests.TestHelpers.TestDoubles.BaseTypes.Common;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using System.Reflection;
